version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/light'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/dark'
    schedule:
      interval: 'daily'
