name: Docker Test Build

on: 
  workflow_dispatch:

env:
  DOCKERHUB_SLUG: xthursdayx/gpodder-docker
  GHCR_SLUG: ghcr.io/xthursdayx/gpodder-docker

jobs:
  build-light-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: DH meta
        id: dh-meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
          flavor: latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.title=gPodder-docker
            org.opencontainers.image.authors=xthursdayx
            org.opencontainers.image.vendor=xthursdayx
            org.opencontainers.image.documentation=https://github.com/xthursdayx/gpodder-docker

      - name: GH meta
        id: gh-meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.GHCR_SLUG }}
          flavor: latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.title=gPodder-docker
            org.opencontainers.image.authors=xthursdayx
            org.opencontainers.image.vendor=xthursdayx
            org.opencontainers.image.documentation=https://github.com/xthursdayx/gpodder-docker

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S%:z')"
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: light
          file: light/Dockerfile
          platforms: linux/amd64
          build-args: BUILD_DATE=${{ steps.date.outputs.date }}
          push: true
          tags: |
            ${{ env.GHCR_SLUG }}:test-light
          labels: ${{ steps.dh-meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-dark-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: DH meta
        id: dh-meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
          flavor: latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.title=gPodder-docker
            org.opencontainers.image.authors=xthursdayx
            org.opencontainers.image.vendor=xthursdayx
            org.opencontainers.image.documentation=https://github.com/xthursdayx/gpodder-docker

      - name: GH meta
        id: gh-meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.GHCR_SLUG }}
          flavor: latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.title=gPodder-docker
            org.opencontainers.image.authors=xthursdayx
            org.opencontainers.image.vendor=xthursdayx
            org.opencontainers.image.documentation=https://github.com/xthursdayx/gpodder-docker

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: dark
          file: dark/Dockerfile
          platforms: linux/amd64
          build-args: BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%S%:z')
          push: true
          tags: |
            ${{ env.GHCR_SLUG }}:test-dark
          labels: ${{ steps.dh-meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
